### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by msabramo**
And then maybe do `python setup.py register` to update PyPI.

### CODE REVIEW

**Comment by teixas** [comment]
Ooops

Seams that I noticed about this PR too late since I've released a new version already ;-)

**Comment by msabramo** [comment]
Oh you can just do `python setup.py register` to update the description without releasing a new version.

**Comment by teixas** [comment]
Oh cool! Didn't know about it.

Anyway I did it and PyPi is rendering the same.

**Comment by teixas** [comment]
Nevermind I was trying to register the wrong package.

Thanks!

**Comment by msabramo** [comment]
Looks great! Glad that you figured it out!

**Pull request merged**
